eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api1:
      path: /api1/**
      serviceId: test-springcloud-client
    api2:
      path: /api2/**
      serviceId: test-springcloud-client1